/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/7.4.2/samples
 */

description = """
Example Gradle project demonstrating the Gradle build for a Java application
Project name: ${project.name}
"""

plugins{
    //Apply the application plugin for building java applications 
    application
    // Ability to publish build artifacts to an Apache Maven repository
    `maven-publish`
}

// Declaring version number
version = '1'

repositories{
    //Use Maven repository to get the libs
    mavenCentral()
}

// Declaring what Java version we are building with
java {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
}

dependencies{

    //Specify the TestNG framework
    testImplementation("org.testng:testng:7.4.0")

    //The dependency also uses the google guava library
    implementation("com.google.guava:guava:30.0-jre")
}

application{
    //Define the main class for the application
    mainClass.set("GradleDemo.App")
}

tasks.test{
    //Use TestNG for unit tests
    useTestNG()

    // show standard out and standard error of the test JVM(s) on the console
    testLogging.showStandardStreams = true
}

