# This is a basic workflow to help you get started with Actions

name: CI with Java and Gradle

# Controls when the workflow will run
on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains three jobs
  build:
    name: Build
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Setup Java
    - uses: actions/checkout@v2
    - name: Setup JDK 11
      uses: actions/setup-java@v2      
      with:
        java-version: 11
        distribution: 'adopt'
        # Using gradle cache to improve efficiencies
        cache: gradle    
      
    # Make gradlew executable
    - name: Make Gradlew executable
      run: chmod +x ./gradlew
    # Run our build using gradle
    - name: Build with Gradle
      run: ./gradlew build
    # Run build with scan in fails
    - if: failure()
      run: ./gradlew build --scan            
        
  # This workflow contains three jobs and an alternative job
  test_job:
    name: Test
    # Depends on assemble_job
    needs: [build]
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Setup Java
    - uses: actions/checkout@v2
    - name: Setup JDK 11
      uses: actions/setup-java@v2      
      with:
        java-version: 11
        distribution: 'adopt'
        cache: gradle
    # Make gradlew executable
    - name: Make Gradlew executable
      run: chmod +x ./gradlew
    # Run test
    - name: Running appHasAGreeting test
      run: ./gradlew test --tests AppTest.appHasAGreeting
    # Open Gradle test report upon fail
    - if: failure()
      run: ls app/build/reports/tests/test/index.html    
          
  # This workflow contains two jobs          
  assemble_job:
    name: Assembly
    # Depends on build job
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      # Saving build log
      - name: Save Build Scan Log
        uses: actions/upload-artifact@v2
        with:
          # Store the output of the build in file
          name: buildscan-assemble
          path: 'buildscan.log'
          # Create warning if file not found
          if-no-files-found: warn
   
  doc_job:
    name: JavaDocs
    runs-on: ubuntu-latest
    needs: [build]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Setup Java
    - uses: actions/checkout@v2
    - name: Setup JDK 11
      uses: actions/setup-java@v2      
      with:
        java-version: 11
        distribution: 'adopt'
        cache: gradle
    # Make gradlew executable
    - name: Make Gradlew executable
      run: chmod +x ./gradlew
    # Generating JavaDocs
    - name: Generate JavaDocs
      run: ./gradlew javadoc
          
